os: linux
language: cpp
dist: trusty
before_install: 
- sudo apt-get -y install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-Linux-x86_64.tar.gz";
      mkdir cmake;
      travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake;
      export PATH=${DEPS_DIR}/cmake/bin:${PATH};
      echo ${PATH};
    fi
- cmake --version

install:
script:
- cmake -E make_directory Build
- cmake -E chdir Build cmake ..
- cd Build
- make
addons:
  apt:
    update: true